routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function(){
    Route::get('/select', 'SelectController@index')->name('select.index');
    Route::post('/select', 'SelectController@selected')->name('select.selected');
    Route::resource('/roles', 'RoleController');
    Route::resource('/companies', 'CompanyController');
    Route::resource('/users', 'UserController');
    Route::resource('/options', 'OptionController');
    Route::resource('/clients', 'ClientController');
    Route::resource('/groups', 'GroupController');
    Route::resource('/vehicles', 'VehicleController');
    Route::resource('/containers', 'ContainerController');
    Route::resource('/video-records', 'VideoRecordController');
    Route::resource('/cameras', 'CameraController');
    Route::resource('/mini-servers', 'MiniServerController');
    Route::resource('/antennas', 'AntennaController');
    Route::post('/image-management', 'FunctionController@imageModal')->name('images.modal');
    Route::post('/image-delete/{id}', 'FunctionController@imagesDestroy')->name('images.delete');

//  Route::get('/company', 'CompanydtController@index');
//  Route::get('/company', 'CompanydtController@getcompany')->name('datatable.company');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Models/Client.php
<?php

namespace Carfid\Models;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $table = 'clients';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'code', 'name', 'phone_number', 'address', 'ruc', 'creator_user',
        'company_id'
    ];

    public function group()
    {
         return $this->belongsToMany('Carfid\Models\Group', 'group_client');
    }

    public function vehicle()
    {
         return $this->hasMany('Carfid\Models\Vehicle');
    }

    public function company()
    {
        return $this->belongsTo('Carfid\Models\Company');
    }

    public function scopeClient($query, $company_id)
    {
        return $query->where('company_id', $company_id);
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace Carfid\Http\Controllers;

use Illuminate\Http\Request;
use Carfid\Http\Controllers\FunctionController;
use Carfid\Models\Client;
use Carfid\Models\Vehicle;
use Carfid\Models\GroupClient;
use Carfid\Http\Requests\Clients\CreateRequest;
use Carfid\Http\Requests\Clients\UpdateRequest;
use Log;
use Auth;
use DB;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!FunctionController::roleValidate(4, 1)) {
            FunctionController::accessDeniedMessage('ClientController');

            return redirect()->route('home');
        }

        $clients = Client::where('company_id', session('company')->id)
        ->get();

        return view('clients.index')->with(['clients' => $clients]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!FunctionController::roleValidate(4, 2)) {
            FunctionController::accessDeniedMessage('ClientController');

            return redirect()->route('home');
        }

        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        if (!FunctionController::roleValidate(4, 2)) {
            FunctionController::accessDeniedMessage('ClientController');

            return redirect()->route('home');
        }

        try {
            DB::beginTransaction();
            $faker = \Faker\Factory::create();

            $request->request->add(['code' => $faker->unique()->regexify('[A-Z0-9]{8}')]);
            $request->request->add(['creator_user' => Auth::user()->email]);
            $request->request->add(['company_id' => session('company')->id]);

            Client::create($request->all());

            DB::commit();

            FunctionController::successMessage($request->name, 'ClientController');

        } catch (\Exception $e) {
            DB::rollBack();
            FunctionController::errorMessage($e, 'ClientController');

            return back();
        }

        return redirect()->route('clients.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!FunctionController::roleValidate(4, 3)) {
            FunctionController::accessDeniedMessage('ClientController');

            return redirect()->route('home');
        }

        $client = Client::FindOrFail($id);

        return view('clients.show')->with(['client' => $client]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!FunctionController::roleValidate(4, 4)) {
            FunctionController::accessDeniedMessage('ClientController');

            return redirect()->route('home');
        }

        $client = Client::FindOrFail($id);

        return view('clients.edit')->with(['client' => $client]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        if (!FunctionController::roleValidate(4, 4)) {
            FunctionController::accessDeniedMessage('ClientController');

            return redirect()->route('home');
        }

        try {
            DB::beginTransaction();

            $client = Client::FindOrFail($id)->update($request->all());

            DB::commit();

            FunctionController::successMessage($request->name, 'ClientController');
        } catch (\Exception $e) {
            DB::rollBack();
            FunctionController::errorMessage($e, 'ClientController');

            return back();
        }

        return redirect()->route('clients.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!FunctionController::roleValidate(4, 5)) {
            FunctionController::accessDeniedMessage('ClientController');

            return redirect()->route('home');
        }

        try {
            DB::beginTransaction();

            $vehicle =  Client::FindOrFail($id)->vehicle;

            if (empty($vehicle[0]->id)) {
                GroupClient::where('client_id', $id)->delete();

                Client::destroy($id);

                DB::commit();

                FunctionController::successMessage($id, 'ClientController');

                return redirect()->route('clients.index');
            }else {
                DB::rollBack();
                FunctionController::noticeMessage($id,'ClientController');
            }

        } catch (Exception $e) {
            FunctionController::errorMessage($e, 'ClientController');
        }

        return redirect()->route('clients.show', $id);
    }
}

resources/views/clients/create.blade.php
@extends('layouts.app')
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />

@section('content')
<div class="sign-in-wrapper">
        <div class="graphs">
            <div class="sign-in-form">
                <div class="sign-in-form-top">
                    <span>Cliente - Nuevo</span>
                    <div class="pull-right">
                        <a href="{{ route('clients.index') }}" type="button" class="btn btn-warning"> <i class="fa fa-reply" aria-hidden="true"></i> Atras</a>                           
                    </div>
                 </div>
                <div class="signin">
                    <div class="log-input">
                    @include('flash::message')
                    @include('errors')
                    <form class="form-horizontal" method="POST" action="{{ route('clients.store') }}">
                        {{ csrf_field() }}
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('phone_number') ? ' has-error' : '' }}">
                            <label for="phone_number" class="col-md-4 control-label">Teléfono</label>
                            <div class="col-md-6">
                                <input id="phone_number" type="text" class="form-control" name="phone_number" value="{{ old('phone_number') }}" autofocus>

                                @if ($errors->has('phone_number'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phone_number') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            <label for="address" class="col-md-4 control-label">Dirección</label>

                            <div class="col-md-6">
                                <textarea id="address" type="text" class="form-control" name="address" value="{{ old('address') }}" required autofocus></textarea>

                                @if ($errors->has('address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('ruc') ? ' has-error' : '' }}">
                            <label for="ruc" class="col-md-4 control-label">RUC</label>

                            <div class="col-md-6">
                                <input id="ruc" type="text" class="form-control" name="ruc" value="{{ old('ruc') }}" autofocus>

                                @if ($errors->has('ruc'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('ruc') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 col-md-offset-4">

                                <button type="submit" class="btn btn-success">
                                    Aceptar
                                </button>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop
@section('scripts')

<script type="text/javascript" src="{{ asset('assets/plugins/jquery-1.11.1.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/plugins/dist/jquery.validate.js') }}"></script>


@endsection

resources/views/clients/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="sign-in-wrapper">
        <div class="graphs">
            <div class="sign-in-form">
                <div class="sign-in-form-top">
                    <span>Clientes - Editar</span>
                    <div class="pull-right">                                     
                        <a href="{{ route('clients.show', $client -> id)}}" class="btn btn-warning" id="atras">
                                    <i class="fa fa-reply" aria-hidden="true"></i> Atrás
                                </a>
                    </div>
                   </div>
                <div class="signin">
                    <div class="log-input">
                    @include('flash::message')
                    @include('errors')
                    <form class="form-horizontal" method="POST" action="{{ route('clients.update', $client -> id) }}">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PUT">

                        <div class="form-group{{ $errors->has('code') ? ' has-error' : '' }}">
                            <label for="code" class="col-md-4 control-label">Código</label>

                            <div class="col-md-6">
                                <input id="code" type="text" class="form-control" name="code" value="{{ $client->code }}" autofocus>

                                @if ($errors->has('code'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('code') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ $client->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('phone_number') ? ' has-error' : '' }}">
                            <label for="phone_number" class="col-md-4 control-label">Número de Teléfono</label>

                            <div class="col-md-6">
                                <input id="phone_number" type="text" class="form-control" name="phone_number" value="{{ $client->phone_number }}" autofocus>

                                @if ($errors->has('phone_number'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phone_number') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                            <label for="address" class="col-md-4 control-label">Dirección</label>

                            <div class="col-md-6">
                                <textarea id="address" type="text" class="form-control" name="address" required autofocus>{{ $client->address }}</textarea>

                                @if ($errors->has('address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('ruc') ? ' has-error' : '' }}">
                            <label for="ruc" class="col-md-4 control-label">RUC</label>

                            <div class="col-md-6">
                                <input id="ruc" type="text" class="form-control" name="ruc" value="{{ $client->ruc }}" autofocus>

                                @if ($errors->has('ruc'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('ruc') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                
                                <button type="submit" class="btn btn-success">
                                    <i class="fa fa-check-circle" aria-hidden="true"></i>
                                    Aceptar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    
@endsection

resources/views/clients/show.blade.php
@extends('layouts.app')

@section('content')
<div class="sign-in-wrapper">
        <div class="graphs">
            <div class="sign-in-form">
                 <div class="sign-in-form-top">
                      <span>Cliente - Ver</span>
				
				<div class="pull-right">
					<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-delete"><i class="fa fa-trash-o" aria-hidden="true"></i> Eliminar</button>
					<a href="{{ route('clients.index')}}" class="btn btn-warning" id="atras"><i class="fa fa-reply" aria-hidden="true"></i> Atrás</a>  
					<a href="{{ route('clients.edit', $client->id) }}" type="button" class="btn btn-primary"> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar</a>
				</div>
                </div>

            
          <div class="signin">
            <div class="log-input">
					@include('flash::message')
					@include('errors')
					<div class="panel-body">
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="amount"><b>Código </b>{{ $client -> code }}</label>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="amount"><b>Nombre</b> {{ $client -> name }}</label>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="amount"><b>Teléfono</b> {{ $client -> phone_number }}</label>
								</div>
							</div>
							<div class="col-md-6">
								<div class="form-group">
									<label for="amount"><b>Dirección</b> {{ $client -> address }}</label>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="amount"><b>RUC</b> {{ $client -> ruc }}</label>
								</div>
							</div>
						</div>
					</div>
				</div>

			<div class="panel panel-default">
				<div class="panel-heading clearfix">
					<h3 class="panel-title pull-left m-t-6">Vehiculos</h3>
				</div>
				<div class="panel-body row">
					<div class="table-responsive">
						<table class="table table-striped table-hover" id="sample_1">
							<thead>
								<tr>
									<th>ID</th>
									<th># Placa</th>
									<th>TAG</th>
									<th>Creador de usuario</th>
									<th>Código del cliente</th>
									<th>Fecha creación</th>
									<th>Fecha modificación</th>
								</tr>
							</thead>
							<tbody>
								@foreach($client -> vehicle as $element)
									<tr>
										<td> <a style="color: #3097D1;" href="{{route('vehicles.show', $element -> id )}}">{{$element -> id}}</a></td>
										<td>{{ $element -> plate_number }}</td>
										<td class="text-capitalize">{{$element -> tag}}</td>
										<td>{{$element -> creator_user }}</td>
										<td>{{$element -> client -> name }}</td>
										<td> {{$element -> created_at}}</td>
										<td> {{$element -> updated_at }}</td>
									</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
      </div>
	</div>
</div>
@stop
@section('modals')
<!-- Modal -->
<!-- MODAL PARA ELIMINAR REGISTRO -->
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modal-delete">
    <form action="{{ route('clients.destroy', $client -> id) }}" method="POST">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="DELETE">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button id="modal-delete" type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Eliminar cliente</h4>
                </div>
                <div class="modal-body">
                    <p>¿Esta seguro de eliminar el cliente <b>{{ $client -> name}}</b>?</p>
                </div>
                <div class="modal-footer text-center">
                    <button type="button" class="btn btn-warning" data-dismiss="modal">Atrás</button>
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </div>
            </div>
        </div>
    </form>
</div>
<!-- END Modal  -->
<!-- END MODAL PARA ELIMINAR REGISTRO -->
@endsection