routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function(){
    Route::get('/select', 'SelectController@index')->name('select.index');
    Route::post('/select', 'SelectController@selected')->name('select.selected');
    Route::resource('/roles', 'RoleController');
    Route::resource('/companies', 'CompanyController');
    Route::resource('/users', 'UserController');
    Route::resource('/options', 'OptionController');
    Route::resource('/clients', 'ClientController');
    Route::resource('/groups', 'GroupController');
    Route::resource('/vehicles', 'VehicleController');
    Route::resource('/containers', 'ContainerController');
    Route::resource('/video-records', 'VideoRecordController');
    Route::resource('/cameras', 'CameraController');
    Route::resource('/mini-servers', 'MiniServerController');
    Route::resource('/antennas', 'AntennaController');
    Route::post('/image-management', 'FunctionController@imageModal')->name('images.modal');
    Route::post('/image-delete/{id}', 'FunctionController@imagesDestroy')->name('images.delete');

//  Route::get('/company', 'CompanydtController@index');
//  Route::get('/company', 'CompanydtController@getcompany')->name('datatable.company');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Models/MiniServer.php
<?php

namespace Carfid\Models;

use Illuminate\Database\Eloquent\Model;

class MiniServer extends Model
{
    protected $table = 'mini_servers';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'fixed_ip', 'user_name', 'password', 'description', 'port', 'creator_user', 'company_id'
    ];

    public function antenna()
    {
         return $this->hasMany('Carfid\Models\Antenna');
    }

    public function company()
    {
         return $this->belongsTo('Carfid\Models\Company');
    }

    public function scopeMiniServer($query, $company_id)
    {
        return $query->where('company_id', $company_id);
    }
}

app/Http/Controllers/MiniServerController.php
<?php

namespace Carfid\Http\Controllers;

use Illuminate\Http\Request;
use Log;
use Auth;
use DB;
use Carfid\Http\Requests\MiniServers\CreateRequest;
use Carfid\Http\Requests\MiniServers\UpdateRequest;
use Carfid\Models\MiniServer;

class MiniServerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!FunctionController::roleValidate(11, 1)) {
            FunctionController::accessDeniedMessage('MiniServerController');

            return redirect()->route('home');
        }

        $mini_servers = MiniServer::miniServer(session('company')->id)->get();

        return view('mini_servers.index')->with(['mini_servers' => $mini_servers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!FunctionController::roleValidate(11, 2)) {
            FunctionController::accessDeniedMessage('MiniServerController');

            return redirect()->route('home');
        }

        return view('mini_servers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        if (!FunctionController::roleValidate(11, 2)) {
            FunctionController::accessDeniedMessage('MiniServerController');

            return redirect()->route('home');
        }

        try {
            DB::beginTransaction();

            $request->request->add(['creator_user' => Auth::user()->email]);
            $request->request->add(['company_id' => session('company')->id]);

            MiniServer::create($request->all());

            DB::commit();

            FunctionController::successMessage($request->user_name, 'MiniServerController');

        } catch (\Exception $e) {
            DB::rollBack();
            FunctionController::errorMessage($e, 'MiniServerController');

            return back();
        }

        return redirect()->route('mini-servers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!FunctionController::roleValidate(11, 3)) {
            FunctionController::accessDeniedMessage('MiniServerController');

            return redirect()->route('home');
        }

        $mini_server = MiniServer::FindOrFail($id);

        return view('mini_servers.show')->with(['mini_server' => $mini_server]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!FunctionController::roleValidate(11, 4)) {
            FunctionController::accessDeniedMessage('MiniServerController');

            return redirect()->route('home');
        }

        $mini_server = MiniServer::FindOrFail($id);

        return view('mini_servers.edit')->with(['mini_server' => $mini_server]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        if (!FunctionController::roleValidate(11, 4)) {
            FunctionController::accessDeniedMessage('MiniServerController');

            return redirect()->route('home');
        }

        try {
            DB::beginTransaction();

            MiniServer::FindOrFail($id)->update($request->all());

            DB::commit();

            FunctionController::successMessage($request->name, 'MiniServerController');

        } catch (\Exception $e) {
            DB::rollBack();

            FunctioNController::errorMessage($e, 'MiniServerController');

            return back();
        }

        return redirect()->route('mini-servers.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!FunctionController::roleValidate(11, 5)) {
            FunctionController::accessDeniedMessage('MiniServerController');

            return redirect()->route('home');
        }

        try {
            DB::beginTransaction();

            $antennas = MiniServer::FindOrFail($id)->antenna;

            if (empty($antennas[0]->id)) {

                MiniServer::destroy($id);

                DB::commit();

                FunctionController::successMessage($id, 'MiniServerController');

                return redirect()->route('mini-servers.index');
            }else {
                FunctionController::noticeMessage($id,'MiniServerController');
            }

        } catch (Exception $e) {
            DB::rollBack();
            FunctioNController::errorMessage($e, 'MiniServerController');
        }

        return redirect()->route('mini-servers.index');
    }
}

resources/views/mini_servers/create.blade.php
@extends('layouts.app')

@section('content')
<div class="sign-in-wrapper">
        <div class="graphs">
            <div class="sign-in-form">
                <div class="sign-in-form-top">
                    <span>Server - Nuevo</span>
                    <div class="pull-right">
                        <a href="{{ route('mini-servers.index') }}" type="button" class="btn btn-warning"> <i class="fa fa-reply" aria-hidden="true"></i> Atrás</a>                           
                    </div>
                 </div>
                <div class="signin">
                    <div class="log-input">
                    @include('flash::message')
                    @include('errors')
                    <form class="form-horizontal" method="POST" action="{{ route('mini-servers.store') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('fixed_ip') ? ' has-error' : '' }}">
                            <label for="fixed_ip" class="col-md-4 control-label">Fixed IP</label>

                            <div class="col-md-6">
                                <input id="fixed_ip" type="text" class="form-control" name="fixed_ip" value="{{ old('fixed_ip') }}" required autofocus>

                                @if ($errors->has('fixed_ip'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('fixed_ip') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('user_name') ? ' has-error' : '' }}">
                            <label for="user_name" class="col-md-4 control-label">Nick Name</label>

                            <div class="col-md-6">
                                <input id="user_name" type="text" class="form-control" name="user_name" value="{{ old('user_name') }}" autofocus>

                                @if ($errors->has('user_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('user_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('port') ? ' has-error' : '' }}">
                            <label for="port" class="col-md-4 control-label">Puerto</label>

                            <div class="col-md-6">
                                <input id="port" type="text" class="form-control" name="port" value="{{ old('port') }}" required autofocus>

                                @if ($errors->has('port'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('port') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Descripción</label>

                            <div class="col-md-6">
                                <textarea id="description" type="text" class="form-control" name="description" value="{{ old('description') }}" autofocus></textarea>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Contraseña</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirmar Contraseña</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-success">
                                    <i class="fa fa-check-circle" aria-hidden="true"></i>
                                    Aceptar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mini_servers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="sign-in-wrapper">
        <div class="graphs">
            <div class="sign-in-form">
                <div class="sign-in-form-top">
                    <span>Serve - Editar</span>
                    <div class="pull-right">
                        <a href="{{ route('mini-servers.show', $mini-server->id) }}" type="button" class="btn btn-warning"> <i class="fa fa-reply" aria-hidden="true"></i> Atrás</a>
                    </div>
                   </div>
                <div class="signin">
                    <div class="log-input">
                    @include('flash::message')
                    @include('errors')
                    <form class="form-horizontal" method="POST" action="{{ route('mini-servers.update', $mini_server -> id) }}">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PUT">

                        <div class="form-group{{ $errors->has('fixed_ip') ? ' has-error' : '' }}">
                            <label for="fixed_ip" class="col-md-4 control-label">Fixed  IP</label>

                            <div class="col-md-6">
                                <input id="fixed_ip" type="text" class="form-control" name="fixed_ip" value="{{ $mini_server->fixed_ip }}" required autofocus>

                                @if ($errors->has('fixed_ip'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('fixed_ip') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('user_name') ? ' has-error' : '' }}">
                            <label for="user_name" class="col-md-4 control-label">Nick Name</label>

                            <div class="col-md-6">
                                <input id="user_name" type="text" class="form-control" name="user_name" value="{{ $mini_server->user_name }}" autofocus>

                                @if ($errors->has('user_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('user_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('port') ? ' has-error' : '' }}">
                            <label for="port" class="col-md-4 control-label">Puerto</label>

                            <div class="col-md-6">
                                <input id="port" type="text" class="form-control" name="port" value="{{ $mini_server->port }}" required autofocus>

                                @if ($errors->has('port'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('port') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Descripción</label>

                            <div class="col-md-6">
                                <textarea id="description" type="text" class="form-control" name="description" autofocus>{{ $mini_server->description }}</textarea>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Contraseña</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirmar Contraseña</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Guardar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/mini_servers/show.blade.php
@extends('layouts.app')

@section('content')
 <div class="sign-in-wrapper">
    <div class="graphs">
        <div class="sign-in-form">
            <div class="sign-in-form-top">
                <span>Mini Servidor -Ver</span>
				<div class="pull-right text-center">
					<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-delete"><i class="fa fa-trash-o" aria-hidden="true"></i> Eliminar</button>
					<a href="{{ route('mini-servers.index') }}" type="button" class="btn btn-warning "><i class="fa fa-reply" aria-hidden="true"></i> Atrás 
					</a>
					<a href="{{ route('mini-servers.edit', $mini_server -> id) }}" type="button" class="btn btn-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar
                    </a>
				</div>
			     <br>
            </div>
            <div class="signin">
                <div class="log-input">
    				@include('flash::message')
    				@include('errors')
    				<div class="form-group">
    				  	<label for="amount">Fixed IP: {{ $mini_server -> fixed_ip }}</label>
    				</div>
    			   	<div class="form-group">
    				 	<label for="amount">Nombre de Usuario: {{ $mini_server -> user_name }}</label>
    			   	</div>
    			   	<div class="form-group">
    				 	<label for="amount">Puerto: {{ $mini_server -> port }}</label>
    			   	</div>
    				<div class="form-group">
    				 	<label for="amount">Descripción: {{ $mini_server -> description }}</label>
    			   	</div>
    		 	</div>
	 	     </div>
       </div>
    </div>
</div>
@stop
@section('modals')
    <!-- Modal -->
    <div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modal-delete">
        <form action="{{ route('mini-servers.destroy', $mini_server->id) }}" method="POST">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="DELETE">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Eliminar Container</h4>
                    </div>
                    <div class="modal-body">
                        <p>¿Esta seguro de eliminar el Mini-servidor<b>{{ $mini_server -> name }}</b>?</p>
                    </div>
                    <div class="modal-footer text-center">
                        <button type="button" class="btn btn-warning" data-dismiss="modal"> <i class="fa fa-reply" aria-hidden="true"></i> Atrás</button>
                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i> Eliminar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- end modal -->
@endsection