routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function(){
    Route::get('/select', 'SelectController@index')->name('select.index');
    Route::post('/select', 'SelectController@selected')->name('select.selected');
    Route::resource('/roles', 'RoleController');
    Route::resource('/companies', 'CompanyController');
    Route::resource('/users', 'UserController');
    Route::resource('/options', 'OptionController');
    Route::resource('/clients', 'ClientController');
    Route::resource('/groups', 'GroupController');
    Route::resource('/vehicles', 'VehicleController');
    Route::resource('/containers', 'ContainerController');
    Route::resource('/video-records', 'VideoRecordController');
    Route::resource('/cameras', 'CameraController');
    Route::resource('/mini-servers', 'MiniServerController');
    Route::resource('/antennas', 'AntennaController');
    Route::post('/image-management', 'FunctionController@imageModal')->name('images.modal');
    Route::post('/image-delete/{id}', 'FunctionController@imagesDestroy')->name('images.delete');

//  Route::get('/company', 'CompanydtController@index');
//  Route::get('/company', 'CompanydtController@getcompany')->name('datatable.company');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Models/VideoRecord.php
<?php

namespace Carfid\Models;

use Illuminate\Database\Eloquent\Model;

class VideoRecord extends Model
{
    protected $table = 'video_records';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nick_name', 'ip_address', 'port', 'user_name', 'password', 'creator_user', 'company_id'
    ];

    public function camera()
    {
         return $this->hasMany('Carfid\Models\Camera');
    }

    public function company()
    {
         return $this->belongsTo('Carfid\Models\Company');
    }

    public function scopeVideoRecord($query, $company_id)
    {
        return $query->where('company_id', $company_id);
    }
}

app/Http/Controllers/VideoRecordController.php
<?php

namespace Carfid\Http\Controllers;

use Illuminate\Http\Request;
use Carfid\Models\VideoRecord;
use Carfid\Http\Requests\VideoRecords\CreateRequest;
use Carfid\Http\Requests\VideoRecords\UpdateRequest;
use Log;
use Auth;
use DB;

class VideoRecordController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!FunctionController::roleValidate(9, 1)) {
            FunctionController::accessDeniedMessage('VideoRecordController');

            return redirect()->route('home');
        }

        $video_records = VideoRecord::videoRecord(session('company')->id)->get();

        return view('video_records.index')->with(['video_records' => $video_records]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!FunctionController::roleValidate(9, 2)) {
            FunctionController::accessDeniedMessage('VideoRecordController');

            return redirect()->route('home');
        }

        return view('video_records.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        if (!FunctionController::roleValidate(9, 2)) {
            FunctionController::accessDeniedMessage('VideoRecordController');

            return redirect()->route('home');
        }

        try {
            DB::beginTransaction();

            $request->request->add(['creator_user' => Auth::user()->email]);
            $request->request->add(['company_id' => session('company')->id]);

            VideoRecord::create($request->all());

            DB::commit();

            FunctionController::successMessage($request->nick_name, 'VideoRecordController');

        } catch (\Exception $e) {
            DB::rollBack();
            FunctionController::errorMessage($e, 'VideoRecordController');

            return back();
        }

        return redirect()->route('video-records.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!FunctionController::roleValidate(9, 3)) {
            FunctionController::accessDeniedMessage('VideoRecordController');

            return redirect()->route('home');
        }

        $video_record = VideoRecord::FindOrFail($id);

        return view('video_records.show')->with(['video_record' => $video_record]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!FunctionController::roleValidate(9, 4)) {
            FunctionController::accessDeniedMessage('VideoRecordController');

            return redirect()->route('home');
        }

        $video_record = VideoRecord::FindOrFail($id);

        return view('video_records.edit')->with(['video_record' => $video_record]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        if (!FunctionController::roleValidate(9, 4)) {
            FunctionController::accessDeniedMessage('VideoRecordController');

            return redirect()->route('home');
        }

        try {
            DB::beginTransaction();

            VideoRecord::FindOrFail($id)->update($request->all());

            DB::commit();

            FunctionController::successMessage($request->name, 'VideoRecordController');

        } catch (\Exception $e) {
            DB::rollBack();

            FunctioNController::errorMessage($e, 'VideoRecordController');

            return back();
        }

        return redirect()->route('video-records.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!FunctionController::roleValidate(9, 5)) {
            FunctionController::accessDeniedMessage('VideoRecordController');

            return redirect()->route('home');
        }

        try {
            DB::beginTransaction();

            $cameras = VideoRecord::FindOrFail($id)->camera;

            if (empty($cameras[0]->id)) {

                VideoRecord::destroy($id);

                DB::commit();

                FunctionController::successMessage($id, 'VideoRecordController');

                return redirect()->route('video-records.index');
            }else {
                FunctionController::noticeMessage($id,'VideoRecordController');
            }

        } catch (Exception $e) {
            DB::rollBack();
            FunctioNController::errorMessage($e, 'VideoRecordController');
        }

        return redirect()->route('video-records.index');
    }
}

resources/views/video_records/create.blade.php
@extends('layouts.app')

@section('content')
<div class="sign-in-wrapper">
        <div class="graphs">
            <div class="sign-in-form">
                <div class="sign-in-form-top">
                    <span>Video Grabador - Nuevo</span> 
                    <div class="pull-right">
                        <a href="{{ route('video-records.index') }}" type="button" class="btn btn-warning"> <i class="fa fa-reply" aria-hidden="true"></i> Atrás</a>
                    </div>
                 </div>
                <div class="signin">
                    <div class="log-input">
                    @include('flash::message')
                    @include('errors')
                    <form class="form-horizontal" method="POST" action="{{ route('video-records.store') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('nick_name') ? ' has-error' : '' }}">
                            <label for="nick_name" class="col-md-4 control-label">Nick Name</label>

                            <div class="col-md-6">
                                <input id="nick_name" type="text" class="form-control" name="nick_name" value="{{ old('nick_name') }}" autofocus>

                                @if ($errors->has('nick_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nick_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('ip_address') ? ' has-error' : '' }}">
                            <label for="ip_address" class="col-md-4 control-label">Dirección IP</label>

                            <div class="col-md-6">
                                <input id="ip_address" type="text" class="form-control" name="ip_address" value="{{ old('ip_address') }}" required autofocus>

                                @if ($errors->has('ip_address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('ip_address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('port') ? ' has-error' : '' }}">
                            <label for="port" class="col-md-4 control-label">Puerto</label>

                            <div class="col-md-6">
                                <input id="port" type="text" class="form-control" name="port" value="{{ old('port') }}" required autofocus>

                                @if ($errors->has('port'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('port') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('user_name') ? ' has-error' : '' }}">
                            <label for="user_name" class="col-md-4 control-label">Nombre de Usuario</label>

                            <div class="col-md-6">
                                <input id="user_name" type="text" class="form-control" name="user_name" value="{{ old('user_name') }}" required autofocus>

                                @if ($errors->has('user_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('user_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Contraseña</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirmar Contraseña</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-success">
                                    <i class="fa fa-check-circle" aria-hidden="true"></i> Aceptar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/video_records/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="sign-in-wrapper">
        <div class="graphs">
            <div class="sign-in-form">
                <div class="sign-in-form-top">
                    <span>Video Grabador - Editar</span>
                    <div class="pull-right">
                        <a href="{{ route('video-records.show', $video-record->id) }}" type="button" class="btn btn-warning"> <i class="fa fa-reply" aria-hidden="true"></i>Atrás</a>
                    </div>
                   </div>
                <div class="signin">
                    <div class="log-input">
                    @include('flash::message')
                    @include('errors')
                    <form class="form-horizontal" method="POST" action="{{ route('video-records.update', $video_record -> id) }}">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PUT">

                        <div class="form-group{{ $errors->has('nick_name') ? ' has-error' : '' }}">
                            <label for="nick_name" class="col-md-4 control-label">Nick Name</label>

                            <div class="col-md-6">
                                <input id="nick_name" type="text" class="form-control" name="nick_name" value="{{ $video_record->nick_name }}" autofocus>

                                @if ($errors->has('nick_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nick_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('ip_address') ? ' has-error' : '' }}">
                            <label for="ip_address" class="col-md-4 control-label">Dirección IP</label>

                            <div class="col-md-6">
                                <input id="ip_address" type="text" class="form-control" name="ip_address" value="{{ $video_record->ip_address }}" required autofocus>

                                @if ($errors->has('ip_address'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('ip_address') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('port') ? ' has-error' : '' }}">
                            <label for="port" class="col-md-4 control-label">Puerto</label>

                            <div class="col-md-6">
                                <input id="port" type="text" class="form-control" name="port" value="{{ $video_record->port }}" required autofocus>

                                @if ($errors->has('port'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('port') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('user_name') ? ' has-error' : '' }}">
                            <label for="user_name" class="col-md-4 control-label">Nombre de Usuario</label>

                            <div class="col-md-6">
                                <input id="user_name" type="text" class="form-control" name="user_name" value="{{ $video_record->user_name }}" required autofocus>

                                @if ($errors->has('user_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('user_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Contraseña</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirmar Contraseña</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-success">
                                    Aceptar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/video_records/show.blade.php
@extends('layouts.app')

@section('content')
 <div class="sign-in-wrapper">
        <div class="graphs">
            <div class="sign-in-form">
                 <div class="sign-in-form-top">
                      <span>Video Grabador - Ver</span>
					<div class="pull-right text-center">
						<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-delete"><i class="fa fa-trash-o" aria-hidden="true"></i> Eliminar</button>
						<a href="{{ route('video-records.index') }}" type="button" class="btn btn-warning">
							<i class="fa fa-reply" aria-hidden="true"></i> Atrás
						</a>
						<a href="{{ route('video-records.edit', $video_record -> id) }}" type="button" class="btn btn-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar</a>

					</div>
				</div>
				<div class="signin">
            <div class="log-input">
				@include('flash::message')
				@include('errors')
				<div class="form-group">
				  	<label for="amount">Nick Name: {{ $video_record -> nick_name }}</label>
				</div>
			   	<div class="form-group">
				 	<label for="amount">Dirección IP: {{ $video_record -> ip_address }}</label>
			   	</div>
			   	<div class="form-group">
				 	<label for="amount">Puerto: {{ $video_record -> port }}</label>
			   	</div>
				<div class="form-group">
				 	<label for="amount">Nombre de Usuario: {{ $video_record -> user_name }}</label>
			   	</div>
		 	</div>
	 	</div>
	</div>
</div>
@stop
@section('modals')
<!-- Modal -->
<!-- MODAL PARA ELIMINAR REGISTRO -->
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modal-delete">
    <form action="{{ route('video-records.destroy', $video_record -> id) }}" method="POST">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="DELETE">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button id="modal-delete" type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Eliminar Video Record</h4>
                </div>
                <div class="modal-body">
                    <p>¿Esta seguro de eliminar el Video Record <b>{{ $video_record -> name}}</b>?</p>
                </div>
                <div class="modal-footer text-center">
                    <button type="button" class="btn btn-warning" data-dismiss="modal">Atrás</button>
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </div>
            </div>
        </div>
    </form>
</div>
<!-- END Modal  -->
<!-- END MODAL PARA ELIMINAR REGISTRO -->
@endsection