routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function(){
    Route::get('/select', 'SelectController@index')->name('select.index');
    Route::post('/select', 'SelectController@selected')->name('select.selected');
    Route::resource('/roles', 'RoleController');
    Route::resource('/companies', 'CompanyController');
    Route::resource('/users', 'UserController');
    Route::resource('/options', 'OptionController');
    Route::resource('/clients', 'ClientController');
    Route::resource('/groups', 'GroupController');
    Route::resource('/vehicles', 'VehicleController');
    Route::resource('/containers', 'ContainerController');
    Route::resource('/video-records', 'VideoRecordController');
    Route::resource('/cameras', 'CameraController');
    Route::resource('/mini-servers', 'MiniServerController');
    Route::resource('/antennas', 'AntennaController');
    Route::post('/image-management', 'FunctionController@imageModal')->name('images.modal');
    Route::post('/image-delete/{id}', 'FunctionController@imagesDestroy')->name('images.delete');

//  Route::get('/company', 'CompanydtController@index');
//  Route::get('/company', 'CompanydtController@getcompany')->name('datatable.company');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Models/Camera.php
<?php

namespace Carfid\Models;

use Illuminate\Database\Eloquent\Model;

class Camera extends Model
{
    protected $table = 'cameras';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'code', 'description', 'enable', 'position', 'creator_user', 'video_record_id'
    ];

    public function videoRecord()
    {
         return $this->belongsTo('Carfid\Models\VideoRecord');
    }

    public function scopeCamera($query, $company_id)
    {
        return $query->select('cameras.*')
        ->join('video_records', 'video_records.id', 'cameras.video_record_id')
        ->where('video_records.company_id', $company_id)
        ->orderBy('position', 'ASC');
    }
}

app/Http/Controllers/CameraController.php
<?php

namespace Carfid\Http\Controllers;

use Illuminate\Http\Request;
use Log;
use Auth;
use DB;
use Carfid\Models\{Camera, VideoRecord};
use Carfid\Http\Requests\Cameras\CreateRequest;
use Carfid\Http\Requests\Cameras\UpdateRequest;

class CameraController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!FunctionController::roleValidate(10, 1)) {
            FunctionController::accessDeniedMessage('CameraController');

            return redirect()->route('home');
        }

        $cameras = Camera::camera(session('company')->id)->get();
        // http://mearenera.zippyttech.com/vertedero/camara.php?n=1

        foreach ($cameras as $camera) {

            $image = file_get_contents("http://admin:arenera123@mearenera.zippyttech.com:8081/PSIA/Streaming/channels/".$camera->id."02/picture?videoResolutionWidth=1920&videoResolutionHeight=1080");
            $encode = base64_encode($image);

            $image = imagecreatefromstring($image);
            $image_p = imagecreatetruecolor(300, 200);
            imagecopyresampled($image_p, $image, 0, 0, 0, 0, 300, 200, 1920, 1080);
            ob_start();
            imagepng($image_p);
            $data = ob_get_contents();
            ob_end_clean();
            $encode2 = base64_encode($data);

            $camera['image'] = $encode;
            $camera['thumb_image'] = $encode2;

        }

        return view('cameras.index')->with(['cameras' => $cameras]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!FunctionController::roleValidate(10, 2)) {
            FunctionController::accessDeniedMessage('CameraController');

            return redirect()->route('home');
        }

        $video_records = VideoRecord::videoRecord(session('company')->id)->get();
        $total_positions = Camera::camera(session('company')->id)->get()->count() + 1;

        return view('cameras.create')->with(['video_records' => $video_records, 'total_positions' => $total_positions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateRequest $request)
    {
        if (!FunctionController::roleValidate(10, 2)) {
            FunctionController::accessDeniedMessage('CameraController');

            return redirect()->route('home');
        }

        try {
            DB::beginTransaction();

            // $faker = \Faker\Factory::create();

            // $request->request->add(['code' => $faker->unique()->regexify('[A-Z0-9]{8}')]);
            $request->request->add(['creator_user' => Auth::user()->email]);
            $request->request->add(['enable' => false]);

            $camera = Camera::where('position', $request->position)->first();

            if (!empty($camera->id)) {
                $camera->position = $request->total_positions;
                $camera->save();
            }

            Camera::create($request->all());

            DB::commit();

            FunctionController::successMessage("Camara: ".$request->code, 'CameraController');

        } catch (\Exception $e) {
            DB::rollBack();
            FunctionController::errorMessage($e, 'CameraController');

            return back();
        }

        return redirect()->route('cameras.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!FunctionController::roleValidate(10, 3)) {
            FunctionController::accessDeniedMessage('CameraController');

            return redirect()->route('home');
        }

        $camera = Camera::FindOrFail($id);

        $image = file_get_contents("http://admin:arenera123@mearenera.zippyttech.com:8081/PSIA/Streaming/channels/".$camera->id."02/picture?videoResolutionWidth=1920&videoResolutionHeight=1080");

        $encode = base64_encode($image);

        $image = imagecreatefromstring($image);
        $image_p = imagecreatetruecolor(300, 200);
        imagecopyresampled($image_p, $image, 0, 0, 0, 0, 300, 200, 1920, 1080);
        ob_start();
        imagepng($image_p);
        $data = ob_get_contents();
        ob_end_clean();
        $encode2 = base64_encode($data);

        $camera['image'] = $encode;
        $camera['thumb_image'] = $encode2;

        return view('cameras.show')->with(['camera' => $camera]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!FunctionController::roleValidate(10, 4)) {
            FunctionController::accessDeniedMessage('CameraController');

            return redirect()->route('home');
        }

        $camera = Camera::FindOrFail($id);
        $video_records = VideoRecord::videoRecord(session('company')->id)->get();
        $total_positions = Camera::camera(session('company')->id)->get()->count();

        return view('cameras.edit')->with([
            'camera' => $camera,
            'video_records' => $video_records,
            'total_positions' => $total_positions
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {
        if (!FunctionController::roleValidate(10, 4)) {
            FunctionController::accessDeniedMessage('CameraController');

            return redirect()->route('home');
        }

        try {
            DB::beginTransaction();

            $camera = Camera::where('position', $request->position)->first();
            $update_camera = Camera::FindOrFail($id);

            if (!empty($camera->id)) {
                $camera->position = $update_camera->position;
                $camera->save();
            }

            Camera::FindOrFail($id)->update($request->all());

            DB::commit();

            FunctionController::successMessage("Camara: ".$request->code, 'CameraController');

        } catch (\Exception $e) {
            DB::rollBack();

            FunctioNController::errorMessage($e, 'CameraController');

            return back();
        }

        return redirect()->route('cameras.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!FunctionController::roleValidate(10, 5)) {
            FunctionController::accessDeniedMessage('CameraController');

            return redirect()->route('home');
        }

        try {
            DB::beginTransaction();

            Camera::destroy($id);

            DB::commit();

            FunctionController::successMessage($id, 'CameraController');

        } catch (Exception $e) {
            DB::rollBack();
            FunctionController::errorMessage($e, 'CameraController');
        }

        return redirect()->route('cameras.index');
    }
}

resources/views/cameras/create.blade.php
@extends('layouts.app')

@section('content')
<div class="sign-in-wrapper">
        <div class="graphs">
            <div class="sign-in-form">
                <div class="sign-in-form-top">
                    <span>Camara - Nuevo</span> 
                    <div class="pull-right">                       
                        <a href="{{ route('cameras.index') }}" type="button" class="btn btn-warning"> <i class="fa fa-reply" aria-hidden="true"></i>Atras</a>                           
                    </div>                   
                 </div>
                <div class="signin">
                    <div class="log-input">
                    @include('flash::message')
                    @include('errors')
                    <form class="form-horizontal" method="POST" action="{{ route('cameras.store') }}" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <input type="hidden" name="total_positions" value="{{$total_positions}}">

                        <div class="form-group{{ $errors->has('video_record_id') ? ' has-error' : '' }}">
                            <label for="video_record_id" class="col-md-4 control-label">DVR</label>

                            <div class="col-md-6">
                                <select id="video_record_id" name="video_record_id" class="form-control" required="required">
                                    <option value="">Seleccione un DVR...</option>
                                    @foreach($video_records as $element)
                                        <option value="{{ $element->id }}">{{ $element -> nick_name }}</option>
                                    @endforeach
                                </select>

                                @if ($errors->has('video_record_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('video_record_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('code') ? ' has-error' : '' }}">
                            <label for="code" class="col-md-4 control-label">Código</label>

                            <div class="col-md-6">
                                <input id="code" type="text" class="form-control" name="code" value="{{ old('code') }}" required autofocus>

                                @if ($errors->has('code'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('code') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Descripción</label>

                            <div class="col-md-6">
                                <textarea id="description" type="text" class="form-control" name="description" value="{{ old('description') }}" autofocus></textarea>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('position') ? ' has-error' : '' }}">
                            <label for="position" class="col-md-4 control-label">Posición</label>

                            <div class="col-md-6">
                                <select id="position" name="position" class="form-control" required="required">
                                    @for ($i=1; $i <= $total_positions; $i++)
                                        <option value="{{ $i }}"
                                        @if ($i == $total_positions)
                                            selected="selected"
                                        @endif>
                                        {{ $i }}</option>
                                    @endfor
                                </select>

                                @if ($errors->has('position'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('position') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-success">
                                    Aceptar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/cameras/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="sign-in-wrapper">
        <div class="graphs">
            <div class="sign-in-form">
                <div class="sign-in-form-top">
                    <span>Camara - Editar</span>
                    <div class="pull-right">
                        <a href="{{ route('cameras.show', $camera->id) }}" type="button" class="btn btn-warning"> <i class="fa fa-reply" aria-hidden="true"></i> Atrás</a>
                    </div>
                   </div>
                <div class="signin">
                    <div class="log-input">
                    @include('flash::message')
                    @include('errors')
                    <form class="form-horizontal" method="POST" action="{{ route('cameras.update', $camera -> id) }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PUT">

                        <div class="form-group{{ $errors->has('video_record_id') ? ' has-error' : '' }}">
                            <label for="video_record_id" class="col-md-4 control-label">DVR</label>

                            <div class="col-md-6">
                                <select id="video_record_id" name="video_record_id" class="form-control" required="required">
                                    <option value="">Seleccione un DVR...</option>
                                    @foreach($video_records as $element)
                                        <option value="{{ $element->id }}"
                                            @if ($element->id == $camera->video_record_id)
                                                selected="selected"
                                            @endif
                                            >{{ $element -> nick_name }}
                                        </option>
                                    @endforeach
                                </select>

                                @if ($errors->has('video_record_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('video_record_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('code') ? ' has-error' : '' }}">
                            <label for="code" class="col-md-4 control-label">Código</label>

                            <div class="col-md-6">
                                <input id="code" type="text" class="form-control" name="code" value="{{ $camera->code }}" required autofocus>

                                @if ($errors->has('code'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('code') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('enable') ? ' has-error' : '' }}">
                            <label for="enable" class="col-md-4 control-label">Estatus</label>

                            <div class="col-md-6">
                                <select id="enable" name="enable" class="form-control" required="required">
                                    <option value="">Seleccione un eenable...</option>
                                    <option value="1"
                                        @if ($camera->enable == 1)
                                            selected="selected"
                                        @endif>Activo
                                    </option>
                                    <option value="0"
                                        @if ($camera->enable == 0)
                                            selected="selected"
                                        @endif>Inactivo
                                    </option>
                                </select>

                                @if ($errors->has('enable'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('enable') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Descripción</label>

                            <div class="col-md-6">
                                <textarea id="description" type="text" class="form-control" name="description"autofocus>{{ $camera->description }}</textarea>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('position') ? ' has-error' : '' }}">
                            <label for="position" class="col-md-4 control-label">Posición</label>

                            <div class="col-md-6">
                                <select id="position" name="position" class="form-control" required="required">
                                    @for ($i=1; $i <= $total_positions; $i++)
                                        <option value="{{ $i }}"
                                        @if ($i == $camera->position)
                                            selected="selected"
                                        @endif>
                                        {{ $i }}</option>
                                    @endfor
                                </select>

                                @if ($errors->has('position'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('position') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-success">
                                    Aceptar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/cameras/show.blade.php
@extends('layouts.app')

@section('content')
 <div class="sign-in-wrapper">
    <div class="graphs">
        <div class="sign-in-form">
            <div class="sign-in-form-top">
                <span>Camara - Ver</span>
				<div class="pull-right ">
					<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-delete"><i class="fa fa-trash-o" aria-hidden="true"></i> Eliminar</button>
					<a href="{{ route('cameras.index') }}" type="button" class="btn btn-warning">
						<i class="fa fa-reply" aria-hidden="true"></i> Atrás
					</a>
					<a href="{{ route('cameras.edit', $camera -> id) }}" type="button" class="btn btn-primary"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Editar</a>
				</div>
            </div>
          	<div class="signin">
	            <div class="log-input">
					@include('flash::message')
					@include('errors')
					<div class="form-group">
					  	<label for="amount">ID: {{ $camera -> id }}</label>
					</div>
				   	<div class="form-group">
					 	<label for="amount">Dirección IP: {{ $camera -> ip_address }}</label>
				   	</div>
				   	<div class="form-group">
					 	<label for="amount">Código: {{ $camera -> code }}</label>
				   	</div>
					<div class="form-group">
					 	<label for="amount">Descripción: {{ $camera -> description }}</label>
				   	</div>
					<div class="form-group">
					 	<label for="amount">Estatus:
							@if ($camera->enable == 1)
								Activa
							@else
								Inactiva
							@endif
						</label>
				   	</div>
					<div class="form-group">
					 	<label for="amount">Posición: {{ $camera -> position }}</label>
				   	</div>
					<div class="form-group">
						<img class="image-thumbnail" src="data:image/jpeg;base64,{!!$camera->thumb_image!!}" alt="prueba">
				   	</div>
			 	</div>
	 		</div>
		</div>
	</div>
</div>
@stop
@section('modals')
<!-- Modal -->
<!-- MODAL PARA ELIMINAR REGISTRO -->
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modal-delete">
    <form action="{{ route('cameras.destroy', $camera -> id) }}" method="POST">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="DELETE">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button id="modal-delete" type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Eliminar Camara</h4>
                </div>
                <div class="modal-body">
                    <p>¿Esta seguro de eliminar la Camara <b>{{ $camera -> name}}</b>?</p>
                </div>
                <div class="modal-footer text-center">
                    <button type="button" class="btn btn-warning" data-dismiss="modal">Atrás</button>
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </div>
            </div>
        </div>
    </form>
</div>
<!-- END Modal  -->
<!-- END MODAL PARA ELIMINAR REGISTRO -->
@endsection